### PR TITLE
add contributor fenixinc+russian translation

### PR DESCRIPTION
**Pull request by FenixInc220**
Hello! I made a translation for your mod into Russian, and also added my nickname to the factory file

### CODE REVIEW

**Comment by Sjouwer** [comment]
Hey, thank you for the PR.
The translations look fine, though it seems like your PR is based on an older version.
Because of that, the fabric.mod.json file has quite a few unwanted changes:
https://github.com/Sjouwer/gamma-utils/pull/30/files#diff-882c6606823cf6c4e4114c1125850a04ed3180c48aef0e1467f1e4022b235db2
Please make sure the only change in that file is adding your name and revert all other changes.

You also seem to be missing translations for these:
```
"text.autoconfig.gamma_utils.option.advancedOptions.showNightVisionIcon": "Show Night Vision Icon",
"text.autoconfig.gamma_utils.option.advancedOptions.showNightVisionIcon.@Tooltip": "Show the Night Vision icon in the upper \nright corner like a real status effect",
```

**Review by FenixInc220 — COMMENTED** [review]
changes have been made, all changes except the nickname have been canceled, and translation of 2 missing lines has been added

**Comment by Sjouwer** [comment]
Looking good now, it's been merged, thank you!

**Comment by Felix14-v2** [comment]
Now I have to fix that...

**Comment by Sjouwer** [comment]
Hey @Felix14-v2, are the translations that bad? I just put them into google translate to see if they at least didn't translate to some nonsense. However I sadly don't know Russian and can't judge the quality of the translations. If you're willing to fix them I would very much appreciate that

**Pull request merged**
